"""
Django settings for dialer_dashboard project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:          # python-dotenv optional
    load_dotenv = None


def _flag(name, default):
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def _list(name, default=""):
    return [v.strip() for v in os.getenv(name, default).split(",") if v.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#: The scraper project root, one level up. Both the scrapers and this site
#: read the same .env file, so there is a single place to change a secret.
PROJECT_ROOT = BASE_DIR.parent
if load_dotenv is not None:
    load_dotenv(PROJECT_ROOT / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _flag("DJANGO_DEBUG", False)

# Requirement 6: LAN access. Django serves only the hosts listed here and
# answers anything else with 400 Bad Request, so the server's LAN address has
# to appear in this list; with localhost alone no other machine can load the
# dashboard.
ALLOWED_HOSTS = _list("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,10.140.28.15")

# CSRF checking needs a full origin including the scheme, not just a host
# name. The login form and every POST API are validated against this list.
CSRF_TRUSTED_ORIGINS = _list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1,http://localhost,http://10.140.28.15",
)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'monitoring',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Nginx serves /static/ in production and never passes those requests
    # through, so this normally does nothing. It matters when Nginx is not in
    # front - a direct Gunicorn run, or a proxy that is down for a reload -
    # because Django itself refuses to serve static files with DEBUG off, and
    # a dashboard whose JavaScript 404s looks alive but never updates.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dialer_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dialer_dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Requirement 2: PostgreSQL. Until Postgres is installed the models still
# validate and run on SQLite. Setting DB_ENGINE=postgres switches the backend
# over with no code change.
if os.getenv("DB_ENGINE", "sqlite").lower().startswith("post"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "dialer_dashboard"),
            "USER": os.getenv("DB_USER", "dialer"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "CONN_MAX_AGE": 60,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

def _system_timezone():
    """The machine's IANA zone, e.g. "Asia/Kolkata"."""
    try:
        name = Path("/etc/timezone").read_text().strip()
        if name:
            return name
    except OSError:
        pass
    try:
        # /etc/localtime is a symlink into the zoneinfo database.
        link = os.readlink("/etc/localtime")
        if "zoneinfo/" in link:
            return link.split("zoneinfo/", 1)[1]
    except OSError:
        pass
    return "UTC"


# Pinning this to UTC while the scrapers use the machine's clock would split
# the two: the dashboard would decide "yesterday" from one zone and the
# scrapers from another. Following the system keeps them in step, so changing
# the server's timezone moves the whole stack together.
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE") or _system_timezone()

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# The scrapers send their own alerts directly over SMTP; Django only needs a
# working backend so server errors can be mailed to ADMINS. It reuses the
# credentials already in .env rather than introducing a second set.
if os.getenv("SMTP_HOST"):
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'HOST': os.getenv("SMTP_HOST"),
            'PORT': int(os.getenv("SMTP_PORT", "587")),
            'USERNAME': os.getenv("EMAIL_SENDER", ""),
            'PASSWORD': os.getenv("EMAIL_PASSWORD", ""),
            'USE_TLS': True,
            'TIMEOUT': 20,
        },
    }
    DEFAULT_FROM_EMAIL = os.getenv("EMAIL_SENDER", "root@localhost")
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
else:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }


# ---------------------------------------------------------------------------
# Monitoring settings
# ---------------------------------------------------------------------------

#: Requirement 11 - a RUNNING job with no heartbeat for this long is swept
#: to NOT_RESPONDING, which is how a killed or hung scraper stops looking busy.
HEARTBEAT_TIMEOUT_SECONDS = int(os.getenv("HEARTBEAT_TIMEOUT_SECONDS", "90"))
#: How often a running scraper is expected to send a heartbeat. Keep it well
#: below the timeout above so one dropped beat is not treated as a failure.
HEARTBEAT_INTERVAL_SECONDS = int(os.getenv("HEARTBEAT_INTERVAL_SECONDS", "30"))

#: Shared secret the scrapers present as X-Monitor-Token when posting to the
#: monitoring API (requirements 12 and 16). Never sent to the browser.
MONITOR_API_TOKEN = os.getenv("MONITOR_API_TOKEN", "")

#: Ceiling for one dashboard-triggered scraper run.
RUN_TIMEOUT_SECONDS = int(os.getenv("RUN_TIMEOUT_SECONDS", "1800"))

#: Scraper project root - dashboard yahan se Media/ aur scripts padhta hai.
SCRAPER_ROOT = Path(os.getenv("DIALER_SCRAPPER_ROOT", PROJECT_ROOT))

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Where collectstatic writes the files Nginx serves. It is overridable
# because Nginx runs as www-data and cannot traverse a 750 home directory: in
# deployment this points at /var/www/dialer-dashboard/static, a directory
# owned by this user and readable by the web server, so collectstatic still
# needs no sudo and the home directory stays private.
STATIC_ROOT = Path(os.getenv("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles"))

# Hashed filenames let both Nginx and the browser cache aggressively without
# ever serving a stale file: changing dashboard.js changes its URL, so the
# kiosk picks up a deploy without anyone clearing a cache.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Behind Nginx the connection Django sees is the one from the proxy, so the
# real client scheme and host have to be taken from the forwarded headers.
# Gunicorn only accepts those headers from loopback (forwarded_allow_ips),
# which is what stops a client from forging them.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ---------------------------------------------------------------------------
# Channels / WebSocket (requirement 3)
# ---------------------------------------------------------------------------

ASGI_APPLICATION = "dialer_dashboard.asgi.application"

# Redis is the production channel layer: it is what lets a scraper callback
# arriving at one worker reach a browser connected to another. The in-memory
# layer is a single-process fallback so the stack runs before Redis is
# installed - it must NOT be used with more than one worker.
if os.getenv("CHANNEL_LAYER", "memory").lower().startswith("redis"):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(os.getenv("REDIS_HOST", "127.0.0.1"),
                           int(os.getenv("REDIS_PORT", "6379")))],
            },
        }
    }
else:
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}


# ---------------------------------------------------------------------------
# Transport security
# ---------------------------------------------------------------------------

# This deployment is HTTP-only on a private LAN: there is no certificate for
# 10.140.28.15, so redirecting to HTTPS or marking the cookies secure would
# lock everyone out rather than protect them. The settings are still written
# out in full, gated on one flag, so putting a certificate in front of Nginx
# later is a single change here and in the site config.
SECURE_SSL = _flag("DJANGO_SECURE_SSL", False)

SECURE_SSL_REDIRECT = SECURE_SSL
SESSION_COOKIE_SECURE = SECURE_SSL
CSRF_COOKIE_SECURE = SECURE_SSL
SECURE_HSTS_SECONDS = 31536000 if SECURE_SSL else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL
SECURE_HSTS_PRELOAD = SECURE_SSL

if not SECURE_SSL:
    # Silenced knowingly, and only while the site is plain HTTP. Each of these
    # warns about a protection that requires TLS to mean anything; flipping
    # DJANGO_SECURE_SSL=true re-enables both the settings and the checks.
    SILENCED_SYSTEM_CHECKS = [
        "security.W004",   # HSTS
        "security.W008",   # SSL redirect
        "security.W012",   # secure session cookie
        "security.W016",   # secure CSRF cookie
    ]

# Protections that do not need TLS, so they are on unconditionally.
SESSION_COOKIE_HTTPONLY = True      # the session cookie is unreadable from JS
CSRF_COOKIE_HTTPONLY = False        # dashboard.js must read it to POST
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"   # the dashboard never frames itself

# Idle sessions on a kiosk screen should not stay valid forever.
SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", str(12 * 60 * 60)))

