# Generated by Django 6.1.1 on 2026-09-12 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('schedule_type', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manually triggered'), ('CONTINUOUS', 'Continuous'), ('ONE_TIME', 'One-time')], default='SCHEDULED', max_length=16)),
                ('script_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'processes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(help_text='Report date (usually yesterday)')),
                ('run_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('NOT_RESPONDING', 'Not Responding')], db_index=True, default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_scraped', models.IntegerField(default=0)),
                ('records_uploaded', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('evidence_path', models.CharField(blank=True, default='', max_length=255)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='monitoring.process')),
            ],
            options={
                'ordering': ['-run_date', '-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('stage', models.CharField(blank=True, choices=[('startup', 'Startup'), ('browser_start', 'Browser start'), ('login', 'Login'), ('navigation', 'Navigation'), ('date_selection', 'Date selection'), ('scraping', 'Scraping'), ('download', 'Download'), ('validation', 'Validation'), ('processing', 'Processing'), ('hrms_upload', 'HRMS upload'), ('completed', 'Completed')], default='', max_length=32)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=8)),
                ('message', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.processrun')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['run_date', 'status'], name='monitoring__run_dat_cfb834_idx'),
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['process', 'run_date'], name='monitoring__process_5ec2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='processlog',
            index=models.Index(fields=['run', 'timestamp'], name='monitoring__run_id_b32314_idx'),
        ),
    ]
