# Generated by Django 6.1.1 on 2026-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='script_path',
        ),
        migrations.AddField(
            model_name='process',
            name='file_pattern',
            field=models.CharField(blank=True, default='{date}_APR.csv', max_length=128),
        ),
        migrations.AddField(
            model_name='process',
            name='output_dir',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='process',
            name='range_aware',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='script_name',
            field=models.CharField(blank=True, default='script.py', max_length=64),
        ),
        migrations.AddField(
            model_name='process',
            name='working_dir',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
