# Generated by Django 6.1.1 on 2026-09-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_process_script_path_process_file_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='kind',
            field=models.CharField(choices=[('SCRAPER', 'Scraper'), ('WORKFLOW', 'Workflow step')], default='SCRAPER', max_length=16),
        ),
    ]
