# Generated by Django 6.1.1 on 2026-09-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_process_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='kind',
            field=models.CharField(choices=[('SCRAPER', 'Scraper'), ('CLEANER', 'APR cleaner'), ('WORKFLOW', 'Workflow step')], default='SCRAPER', max_length=16),
        ),
    ]
